// writes the KLIN brand-kit scenes into _studio/src (then: node _studio/render.js)
const fs = require('fs'), path = require('path'); const S = path.join(__dirname, 'src');
const X = process.env.X_HANDLE || '@KlinOnRH', DOMAIN = process.env.DOMAIN || '';
const mark = (px) => `<span class="kiln" style="width:${px}px;height:${px}px"></span>`;
const foot = `<div class="abs mono" style="left:130px;right:130px;bottom:80px;display:flex;justify-content:space-between;align-items:center;font-size:26px;color:#948a7c"><span style="display:flex;align-items:center;gap:22px;color:#1f1b18;font-family:'Fraunces';font-weight:700;font-size:32px;letter-spacing:.04em;text-transform:none">${mark(44)}KLIN</span><span>${DOMAIN ? DOMAIN + ' · ' : ''}${X} · $KLIN</span></div>`;
const page = (body, css = '') => `<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="_base.css"><style>body{width:2400px;height:1350px}.pad{position:absolute;inset:110px 130px}.kick{font-family:'JetBrains Mono';font-size:24px;letter-spacing:.3em;text-transform:uppercase;color:#948a7c}${css}</style><body><div class="grain"></div><div class="glow" style="right:-300px;top:-300px"></div>${body}${foot}`;
const w = (f, s) => fs.writeFileSync(path.join(S, f), s);

w('klin-pfp.html', `<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="_base.css"><style>body{width:2000px;height:2000px;display:grid;place-items:center}</style><body><div class="grain"></div><div class="glow" style="left:300px;top:300px"></div>${mark(1150)}`);
w('klin-banner.html', `<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="_base.css"><style>body{width:3000px;height:1000px}</style><body><div class="grain"></div><div class="glow" style="right:-200px;top:-500px"></div><div class="f abs" style="left:150px;top:190px;font-size:180px">Private compute,<br>fired in a <span class="fi terra">sealed oven.</span></div><div class="abs mono" style="left:158px;bottom:130px;font-size:38px;color:#948a7c">klin · sealed models · lent gpus · private mode · sealed messages${DOMAIN ? ' · ' + DOMAIN : ''}</div><div class="abs" style="right:240px;top:230px">${mark(540)}</div>`);
w('klin-keyart.html', page(`<div class="pad"><div class="kick">private compute · every layer</div><div class="f" style="font-size:146px;margin-top:60px;max-width:1500px">Ask anything.<br><span class="fi terra">Nobody reads it.</span></div><p style="font-size:40px;color:#5f574f;max-width:1150px;margin-top:60px;line-height:1.55">Sealed models, GPUs lent by strangers, a model that never leaves your browser, and messages only the other person can open.</p></div><div class="card abs" style="right:130px;top:300px;width:760px;height:660px;padding:54px"><div class="mono" style="font-size:20px;color:#948a7c">the four rooms</div>${[['01', 'Sealed models', 'prompts sealed before they leave'], ['02', 'Lent GPUs', 'lenders keep 70% per token'], ['03', 'Private mode', 'WebGPU · never leaves the machine'], ['04', 'Sealed messages', 'x25519 · aes-gcm · relay sees bytes']].map((r) => `<div style="display:flex;gap:26px;align-items:baseline;padding:30px 0;border-bottom:2px solid #eae2d5"><span class="mono terra" style="font-size:22px">${r[0]}</span><div><div class="f" style="font-size:40px">${r[1]}</div><div style="font-size:24px;color:#5f574f;margin-top:6px">${r[2]}</div></div></div>`).join('')}</div>`));
const rooms = [['Sealed models', 'Chat through Chutes and Bittensor models. Prompts are sealed before they leave the browser. Real streaming answers, live per-model prices.'], ['Lent GPUs', 'Plug your browser in as a lender over WebSocket. Askers pay per token in credits. The lender keeps 70%, paid on every answer.'], ['Private mode', 'A model runs entirely in your browser over WebGPU. No server, no log, no network. The oven door stays shut.'], ['Sealed messages', 'Peer-to-peer encrypted with X25519 and AES-GCM, padded, relayed through a server that only ever sees opaque bytes. Offline mailbox included.']];
w('klin-rooms.html', page(`<div class="pad"><div class="kick">how it works</div><div class="f" style="font-size:112px;margin-top:40px">Four rooms. <span class="fi terra">One oven.</span></div><div class="g">${rooms.map((r, i) => `<div class="card s"><div class="mono terra" style="font-size:22px">0${i + 1}</div><h2 class="f">${r[0]}</h2><p>${r[1]}</p></div>`).join('')}</div></div>`, `.g{display:grid;grid-template-columns:repeat(4,1fr);gap:28px;margin-top:80px}.s{padding:48px 40px;height:560px}.s h2{font-size:46px;margin:26px 0 22px}.s p{font-size:27px;line-height:1.55;color:#5f574f}`));
w('klin-lend.html', page(`<div class="pad"><div class="kick">lend your gpu</div><div class="f" style="font-size:112px;margin-top:40px">Your GPU is idle.<br><span class="fi terra">Someone is asking.</span></div><div class="card abs" style="left:130px;right:130px;top:470px;height:440px;padding:44px 60px;display:grid;grid-template-columns:1fr 1fr 1fr;gap:40px;align-items:center">${[['70%', 'of every token fee', 'goes to the lender'], ['$0.01', 'per 1,000 tokens', 'asker pays in credits'], ['0', 'servers in the loop', 'browser to browser over one socket']].map((k) => `<div><div class="f terra" style="font-size:130px;line-height:1">${k[0]}</div><div class="f" style="font-size:38px;margin-top:14px">${k[1]}</div><div style="font-size:26px;color:#5f574f;margin-top:6px">${k[2]}</div></div>`).join('')}</div>`));
w('klin-sealed.html', page(`<div class="pad"><div class="kick">sealed messages</div><div class="f" style="font-size:112px;margin-top:40px">The relay carries it.<br><span class="fi terra">It cannot read it.</span></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:60px;margin-top:80px;align-items:start"><p style="font-size:36px;line-height:1.55;color:#5f574f">Keys are made in your browser and never leave it. Every message is padded to a fixed size, encrypted to the other person's key with X25519 and AES-GCM, and handed to the relay as bytes. If they are offline it waits in a mailbox. When they open it, only they can.</p><div class="card" style="padding:44px 50px;font-family:'JetBrains Mono';font-size:26px;line-height:2;color:#1f1b18"><div><span class="dust">from</span>  PUB_ONE…qrstuv</div><div><span class="dust">to</span>    PUB_TWO…qrstuv</div><div><span class="dust">box</span>   <span class="terra">a91f 3c77 0e2b 5d…</span></div><div><span class="dust">relay</span> sees: <span class="ember">bytes</span></div><div><span class="dust">reader</span> sees: "meet at nine"</div></div></div></div>`));
w('klin-private.html', page(`<div class="pad"><div class="kick">private mode</div><div class="f" style="font-size:112px;margin-top:40px">No server.<br>No log. <span class="fi terra">No network.</span></div><div class="card abs" style="left:130px;right:130px;top:470px;height:440px;padding:0;display:grid;grid-template-columns:1fr 1fr;overflow:hidden"><div style="padding:54px 60px"><div class="mono" style="font-size:20px;color:#948a7c">webgpu · in your browser</div><div class="f" style="font-size:54px;margin-top:22px">The model loads once,<br>then the door shuts.</div><p style="font-size:27px;color:#5f574f;margin-top:22px;line-height:1.55">Tokens are generated on your own GPU. Unplug the network after the load and it still answers.</p></div><div style="background:#1f1b18;color:#f3ede3;padding:54px 60px;font-family:'JetBrains Mono';font-size:26px;line-height:2"><div class="dust">&gt; loading Llama-3.2-1B … 100%</div><div class="dust">&gt; network: <span class="ember">offline</span></div><div>&gt; what is a kiln?</div><div class="terra">a sealed oven that fires clay into something that lasts.</div></div></div>`));
let r = fs.readFileSync(path.join(__dirname, 'render.js'), 'utf8');
r = r.replace(/const SIZES = \{[\s\S]*?\};/, "const SIZES = {\n  'klin-pfp': [2000, 2000],\n  'klin-banner': [3000, 1000],\n  'klin-keyart': [2400, 1350],\n  'klin-rooms': [2400, 1350],\n  'klin-lend': [2400, 1350],\n  'klin-sealed': [2400, 1350],\n  'klin-private': [2400, 1350],\n};").replace(/hushchrome_|mutechrome_|cerebrochrome_/g, 'klinchrome_'); fs.writeFileSync(path.join(__dirname, 'render.js'), r);
console.log('kiln kit scenes written (' + X + (DOMAIN ? ' · ' + DOMAIN : '') + ')');
